// <auto-generated />
using ContactManager;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContactManager.Migrations
{
    [DbContext(typeof(ContactDbContext))]
    [Migration("20210524001909_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("ContactManager.Models.Contact", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Email = "fadeniayobami@gmail.com",
                            FirstName = "Ayobami",
                            LastName = "Fadeni",
                            PhoneNumber = "+2348106322363"
                        },
                        new
                        {
                            Id = "2",
                            Email = "afolabiahmed@gmail.com",
                            FirstName = "Afolabi",
                            LastName = "Ahmed",
                            PhoneNumber = "+2348135372863"
                        },
                        new
                        {
                            Id = "3",
                            Email = "ibrahimtope@gmail.com",
                            FirstName = "Ibrahim",
                            LastName = "Tope",
                            PhoneNumber = "+2348165289045"
                        },
                        new
                        {
                            Id = "4",
                            Email = "eugeneuche@gmail.com",
                            FirstName = "Eugene",
                            LastName = "Uche",
                            PhoneNumber = "+2348109873426"
                        },
                        new
                        {
                            Id = "5",
                            Email = "victorumeh@gmail.com",
                            FirstName = "Victor",
                            LastName = "Umeh",
                            PhoneNumber = "+2348035871098"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
